name: Android Appium Tests

on:
  push:
    branches:
      - master

jobs:
  android-tests:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: npm

    - name: Install dependencies
      run: npm ci

    - name: Install Appium
      run: |
        npm install -g appium

    - name: Android Emulator and Tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 33
        target: google_apis
        arch: x86_64
        avd-name: test
        force-avd-creation: true
        cores: 2
        emulator-boot-timeout: 600
        disable-animations: true
        disable-spellchecker: true
        emulator-options: >
          -no-window
          -no-audio
          -no-boot-anim
          -no-snapshot
          -gpu swiftshader_indirect

        script: |
          echo "Emulator started"

          adb devices

          echo "Starting Appium"

          appium --log-level info > appium.log 2>&1 &

          sleep 15

          echo "Running WebdriverIO tests"

          npm run wdio


    - name: Upload Appium logs
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: appium-logs
        path: appium.log