name: Android Appium Tests

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  android-tests:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout repository
      uses: actions/checkout@v4


    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: npm

    - name: Install npm dependencies
      run: npm ci

    - name: Install Android Emulator Image
      run: |
        echo "Installing Android SDK components"

        yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager \
          "platform-tools" \
          "platforms;android-34" \
          "emulator" \
          "system-images;android-34;google_apis;x86_64"

        echo "Android SDK components installed"

    - name: Create Android Emulator
      run: |
        echo "no" | $ANDROID_HOME/cmdline-tools/latest/bin/avdmanager create avd \
          -n test \
          -k "system-images;android-34;google_apis;x86_64" \
          --force

        echo "AVD created"

    - name: Start Android Emulator
      run: |
        echo "Starting emulator"

        nohup $ANDROID_HOME/emulator/emulator \
          -avd test \
          -no-window \
          -no-audio \
          -no-boot-anim \
          -gpu swiftshader_indirect \
          > emulator.log 2>&1 &

        echo "Waiting for emulator"

        adb wait-for-device

        timeout 300 bash -c '
        until adb shell getprop sys.boot_completed | grep -m 1 "1"; do
          echo "Waiting for Android boot..."
          sleep 5
        done
        '

        adb shell input keyevent 82

        adb devices

    - name: Run WebdriverIO Tests
      run: |
        npm run wdio